import type { Metadata } from "next";
import Link from "next/link";
import { Inter, Roboto_Mono } from "next/font/google";
import { NativaGoLogo } from "@/components/NativaGoLogo";
import { LanguageProvider } from "@/lib/i18n/LanguageContext";
import { LanguageSwitcher } from "@/components/LanguageSwitcher";
import "./globals.css";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const robotoMono = Roboto_Mono({
  variable: "--font-roboto-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${robotoMono.variable} antialiased`}
      >
        <LanguageProvider>
          <header className="bg-[#0F1117] py-2 text-sm">
            <div className="mx-auto flex max-w-5xl items-center justify-between px-4">
              <div className="flex items-center gap-2">
                <NativaGoLogo size="sm" context="onDark" />
                <span className="text-xs font-semibold text-emerald-400 bg-emerald-900/40 rounded px-2 py-0.5">CMS</span>
              </div>
              <div className="flex items-center gap-3">
                <LanguageSwitcher variant="dark" />
                <Link
                  href="/login"
                  className="rounded-md border border-white/20 px-3 py-1 text-xs font-medium text-white/70 hover:bg-white/10"
                >
                  Login
                </Link>
              </div>
            </div>
          </header>
          {children}
        </LanguageProvider>
      </body>
    </html>
  );
}
