import type { Metadata } from "next";
import Link from "next/link";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="border-b border-zinc-200 bg-white/80 py-3 text-sm text-zinc-800">
          <div className="mx-auto flex max-w-5xl items-center justify-between px-4">
            <span className="font-semibold">NativaGo CMS</span>
            <div className="flex items-center gap-2">
              {/* Only show login button, remove Admin CMS button */}
              <Link
                href="/login"
                className="rounded-md border border-zinc-300 px-3 py-1 text-xs font-medium text-zinc-700 hover:bg-zinc-50"
              >
                Login
              </Link>
            </div>
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
